To be capable of writing libraries, I have to be capable of reading them first !

#### What are libraries and modules ?
- In Python, a module is a file containing Python code. It can define functions, classes, variables, and other objects that can be used in your Python programs.

- Note that, in libraries such data sets are also available.

#### Iris data set.
- Generally used in practising machine learning algorithms.
- Each data has 4 columns, with each column representing sepal length , sepal width , petal length and petal width respectively
- Study the following code to acquat ur self with similar situations.

In [117]:
# To load the following import the data set
import numpy as np
from sklearn.datasets import load_iris
# note that there are other data-sets as well.

iris_data = load_iris()
iris_data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

$\color{red}{\textbf{Doubt}}$
Why do we need to scale our data?

#### Generating a random matrix in python
- **SYNTAX**
    - `random_matrix = np.random.rand(# of rows,# of cols)`
- Concept of seeding
    - **SYNTAX**
        - `np.rand.seed(any_integer)`
        
- Once u use a seed its value remains the same everytime the code is run.


- **NOTE**
    - When I have a random number generator, then the sequence of random numbers generated are the same but not the random numbers themselves. 
    - When it sees the seed command, it will have a list of random numbers that it should generate.
- Let's demonstrate by using an example. We will make 3 random matrices and out of which two have the same seed.

In [100]:
np.random.seed(0)
rn1 = np.random.rand(1)
rn2 = np.random.rand(1)
np.random.seed(0)
rn3 = np.random.rand(1)

In [101]:
print(f"random #1-random #2", rn1-rn2)
print(f"random #1 - random #3", rn1-rn3)

random #1-random #2 [-0.16637586]
random #1 - random #3 [0.]


**NOTE** The above result doesn't change any number of times i run the code.

We demonstrate the same for higher dimensions.

In [102]:
# consider a random 5*5 matrix
np.random.seed(1)
random_matrix_1 = np.random.rand(5,5)

np.random.seed(2)
random_matrix_2 = np.random.rand(5,5)

np.random.seed(1)
random_matrix_3 = np.random.rand(5,5)

In [104]:
print(f"difference between Random matrix 1 and random matrix 3 = ",random_matrix_1 - random_matrix_3)

print(f"difference between Random matrix 1 and random matrix 2 = ",random_matrix_1 - random_matrix_2)


difference between Random matrix 1 and random matrix 3 =  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
difference between Random matrix 1 and random matrix 2 =  [[-0.0189729   0.69439826 -0.5495481  -0.13298982 -0.27361191]
 [-0.23799623 -0.01838842 -0.27371024  0.0971128   0.27198946]
 [-0.20193932  0.15607741  0.0698723   0.36453932 -0.15705227]
 [-0.11486764 -0.43667049  0.06445299 -0.70617455  0.11845601]
 [ 0.29549848  0.90297507 -0.11469815  0.5957917   0.74922918]]


Therefore same seed value implies same data is genreated.

#### Column wise Min and Max values
- **SYNTAX**
    - `matrix_name.min(axis = Axis #)`
    - `matrix_name.max(axis = Axis #)`
- **Note**
    - This is intuitively clear until dimension 3. Later on it gets slightly tidious to think.
    - The axis# indicates that, keeping all other inidces fixed, vary only the index whose value is axis#.
    
Let us demonstrate the same using random_matrix_1 we generated in the above example.



In [106]:
random_matrix_1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01],
       [4.19194514e-01, 6.85219500e-01, 2.04452250e-01, 8.78117436e-01,
        2.73875932e-02],
       [6.70467510e-01, 4.17304802e-01, 5.58689828e-01, 1.40386939e-01,
        1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01,
        8.76389152e-01]])

In [30]:
random_matrix_1.min(axis=0)

array([9.23385948e-02, 1.86260211e-01, 1.14374817e-04, 1.40386939e-01,
       2.73875932e-02])

It gives us a 1 d array whose elements are minimum values across different columns.

In [105]:
random_matrix_1.max(axis=1)

array([0.72032449, 0.53881673, 0.87811744, 0.67046751, 0.96826158])

Let's observe for a higher dimensional case.

In [113]:
random_matrix_4 = np.random.rand(3,3,3)
random_matrix_4

array([[[0.23984776, 0.49376971, 0.61995572],
        [0.8289809 , 0.15679139, 0.0185762 ],
        [0.07002214, 0.48634511, 0.60632946]],

       [[0.56885144, 0.31736241, 0.98861615],
        [0.57974522, 0.38014117, 0.55094822],
        [0.74533443, 0.66923289, 0.26491956]],

       [[0.06633483, 0.3700842 , 0.62971751],
        [0.21017401, 0.75275555, 0.06653648],
        [0.2603151 , 0.80475456, 0.19343428]]])

In [114]:
random_matrix_4.min(axis=0)

array([[0.06633483, 0.31736241, 0.61995572],
       [0.21017401, 0.15679139, 0.0185762 ],
       [0.07002214, 0.48634511, 0.19343428]])

We are very clear about using min and max now.

#### MINMAX scaler in sklearn

Note that MinMaxScaler is a class in Python.
- In the below example the class MinMaxScaler has two methods.
    - fit = Determines the min and max values.
    - transform = transforms the values to a particular scalar.
- **SYNTAX** for calling the class
    - `instance_name = MinMaxScaler(feature_range= (0,1))`
    - by default the feature range is (0,1)
- Without executing fit method we cannot ofcourse do the transform method.


In [131]:
from sklearn.preprocessing import MinMaxScaler
data = iris_data.data

scaler = MinMaxScaler()
scaler.fit(data)
scaled_data = scaler.transform(data)
scaled_data

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

While executing the above code we saw that scaler.transfor(data) when done before scaler.fit(data). It shows that two methods can be dependent on each other and i would like to do an example problem to understan the same.

In [139]:
# lets define a dummy class
class Dummy():
    def __init__(self, input1, input2):
        self.val1 = input1
        self.val2 = input2
    
    def process1(self, input3):
        process1_output = input3 * self.val1 + self.val2
        self.val3 = process1_output
        return process1_output
    
    def process2(self):
        process2_output = self.val3 + self.val1
        return process2_output
    
dummy_instance = Dummy(2, 3)
dummy_instance.process2()  # This will raise a ValueError


AttributeError: 'Dummy' object has no attribute 'val3'

In [140]:
dummy_instance.process1(2)

7

In [141]:
dummy_instance.process2()

9

Note that an error has been raised when the method process2() was executed before executing method process1().