# Arrays

## Numpy arrays.

### Declaring arrays of specific data type.
- **SYNTAX**
    - `array_name = np.array(dict_name, dtype=np.data_type)`
- Lets define an array from a dictionary whose elements are flaoting point numbers but give the array a data type of int32.


In [4]:
import numpy as np

dict1 = [1.1,2.4,6.5,1.99]
array1 = np.array(dict1,dtype = np.int32)
print(f"array1 = ", array1 )

array1 =  [1 2 6 1]


Note that we get the fraction part removed.

###  (Review) Checking the data tpe of any object

In [5]:
type(array1)

numpy.ndarray

### Changing the datatype of an array
- **SYNTAX**
    - `new_array = old_array.astype(np.new_data_type)`
- *EXAMPLE*
    - Lets us change the data type of array1 to float32 and save it as array2.

In [7]:
array2 = array1.astype(np.float32)
print(f"array2 = ", array2)

array2 =  [1. 2. 6. 1.]


### Deleting elements of an array
- **SYNTAX**
    - `new_array = np.delete(old_array,index)`
- *EXAMPLE*
    - Lets delete 2nd element in the array 2 we created to produce array 3.

In [25]:
array3 = np.delete(array2,[1,-1])
print(f"array2 = ", array2)
print(f"array2 with element in index 1 and the last element \n removed is ",array3)

array2 =  [1. 2. 6. 1.]
array2 with element in index 1 and the last element 
 removed is  [1. 6.]


### FInding index of an element in an array
- **SYNTAX**
    - `index = np.where(array_name== number)`
- *EXAMPLE*
    - Let us find out the index of 1 in the array2.

In [29]:
index_of_1 = np.where(array1==1)
print(f"array1 is ", array1)
print(f"indices of 1s in array1 are",index_of_1)

array1 is  [1 2 6 1]
indices of 1s in array1 are (array([0, 3]),)


### Increasing dimension of an array
- **SYNTAX**
    - `new_array = arr[old_array,axis=axis_number] `
- *EXAMPLE*
    - Let us make a 2d array and see how adding new dimension works.

In [54]:
# Create a 1D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Add a new axis to convert it to a 2D array with a single column
arr_3d = np.expand_dims(arr_1d, axis=2)

print("Original array shape:", arr_2d.shape)
print("3D array shape:", arr_3d.shape)
print("2D array:\n", arr_3d)


Original array shape: (3, 3)
3D array shape: (3, 3, 1)
2D array:
 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]


In [55]:
np.expand_dims(arr_1d, axis=0)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [56]:
np.expand_dims(arr_1d, axis=1)

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

## (REVIEW) Tensor:
### Declaring tensors
- *Example*
    - Lets create a tensor from dict1 qwith float64 datatype. 

In [30]:
import torch
tensor1 = torch.tensor(dict1, dtype = torch.float64)
print(f"tensor1=",tensor1)

tensor1= tensor([1.1000, 2.4000, 6.5000, 1.9900], dtype=torch.float64)


### Changing tensor data type using 2 methods
- torch.type method
- torch.to method
    - *EXAMPLE*
        - Lets change the data type of tensor1 using both the methods to int32. We will create tensor2 from tensor1 using type method, and tensor3 using to method.ensor

In [15]:
tensor2 = tensor1.type(torch.int32)
print(f"Using type method tensor2 is",tensor2)

Using type method tensor2 is tensor([1, 2, 6, 1], dtype=torch.int32)


In [16]:
tensor3 = tensor1.to(torch.int32)
print(f"Using type method tensor3 is",tensor3)

Using type method tensor3 is tensor([1, 2, 6, 1], dtype=torch.int32)
